project: Chest-X-Ray-Pathology-Classifier
program: train_model.py
method: random
name: hparam_tuning
description: testing out the hyperparameters optimization with random method
metric:
  name: valid AUC
  goal: maximize
parameters: 
  batch_size: 
    values: [8, 16]
  epochs:
    values: [5, 10, 15]
  lr: 
    max: 0.1
    min: 0.0001
    distribution: log_uniform_values
  optimizer:
    values: ["Adam", "SGD"]
command:
  - /home/lucas/Projects/x-ray/Chest-X-Ray-Pathology-Classifier/env/bin/python3
  - ${program}
  - "-u"
  - "U-Zeros"
early_terminate:
  type: hyperband
  min_iter: 3