project: Chest-X-Ray-Pathology-Classifier
program: train_model.py
method: random
name: hparam_tuning
description: testing out the hyperparameters optimization with random method
metric:
  name: valid AUC
  goal: maximize
parameters: 
  batch_size: 
    values:
      - 16
      - 32
      - 64
  epochs:
    values: [10, 15]
  lr: 
    max: 0.1
    min: 0.0001
    distribution: log_uniform_values
  optimizer:
    values: ["Adam"]
command:
  - python
  - ${program}
  - "-u"
  - "U-Ignore"
early_terminate:
  type: hyperband
  min_iter: 3