split: "train" # (str) 'train' or 'valid'

data:
  data_path: "gs://chexpert_images_database" # (str) Path to CSV metadata file without trailing slash
  split: train # (str) split to load: train, valid ou test
  resize: [224, 224] # (tuple) Resize dimensions
  gcp_project_id: 'labshurb'
  gcp_bucket: 'chexpert_images_database'

train:
  epochs: 5 # (int) Number of training epochs
  learning_rate: 4e-4 # (float) Learning rate
  gradient_accumulation: 64 # (int) Gradient accumulation steps
  batch_size: 4 # (int) Batch size
  job_dir: "." # (str) Directory to store saved model
  uncertainty_policy: "U-Ignore" # (str) Uncertainty policy
  checkpoint: "google/vit-base-patch16-224" # (str) Model checkpoint

wandb:
  project: "chexpert-vit"
  job_type: "train"
