method: bayes
program: train_vit.py
project: vit_xray
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
parameters:
  epochs:
    value: 10
  lr:
    value: 4e-4
  grad_acc:
    values:
      - 64
  batch_size:
    values:
      - 4
metric:
  name: 'eval/f1_mean'
  goal: 'maximize'
early_terminate:
  type: hyperband
  min_iter: 3